version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./01-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./01-mosquitto/users:/mosquitto/config/users
      - /var/mosquitto/data:/mosquitto/data
      
    restart: always

  influxdb:
    image: influxdb:1.11.8
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - /var/mosquitto/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:6.7.6
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - /var/mosquitto/grafana:/var/lib/grafana
    restart: always

  mqttbridge:
    build: ./02-bridge
    image: mysticrenji/mqttbridgegrafana 
    container_name: mqttbridge
    depends_on:
      - mosquitto
      - influxdb
    restart: always
  

